[project]
name = "keyword-analysis"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "google-ads>=32.0.0",
    "google-auth-oauthlib>=1.4.1",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
]

[project.scripts]
kwa = "kwa.cli:main"

[build-system]
requires = ["uv_build>=0.11.15,<0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "kwa"
